### ISSUE TITLE
renders without dataset/attrs

### ISSUE THREAD

**Issue by janat08** [codemeasandwich/hyper-element#1]
Will render without dataset causing errors, screwing jquery for life.

**Comment by codemeasandwich** [comment]
Can you be clear in what the Issue is? 
If you are having a problem, please provide a code example in jsfiddle or jsbin.

**Comment by janat08** [comment]
There is call to render in middle of it's modification in your library that happens before dataset is parsed or something, all I know is that there're two calls to render in some section of code. You can just log dataset.

**Comment by codemeasandwich** [comment]
Just tested v0.6.0 in FireFox & Chrome and seams ok.  
What browser & OS are you using? Also an example of you failing code would help

**Comment by janat08** [comment]
I also used 0.6 on chrome with windows 10. I had jquery self-executing/immediately-invoked function in body of render function. the dataset was passed in from mobx from wire in loop. The code in question is gone though.

**Comment by codemeasandwich** [comment]
Why are you using jquery in your element? 
Also the "dataset" is part of the Dom & element, not mobx. 
To help you I really need to see some code that you are having a problem with.

**Comment by janat08** [comment]
I just realized jquery won't fly. I imagine there's no way in which you could responsible for dataset being undefined on the first render if you don't meddle with it, thank you for your time.
